### ISSUE TITLE
Custom programs list

### ISSUE THREAD

**Issue by BRO-T** [davestewart/classic-shell-win10#5]
We love your skin, however we want to customise what programs a user can see. I have tried using ClasicShells' gpo's and the best i can get is All programs or nothing. Please help

**Comment by davestewart** [comment]
Hey Bro-T,

I don't think you can customise what is seen in All Programs though, as that's simply part of the OS.

If you want to customise what you see in the Classic Shell menu, use the Classic Shell options.

Sorry to not be more help!
