### ISSUE TITLE
I'm working on a follow-up to this skin.

### ISSUE THREAD

**Issue by bonzibudd** [davestewart/classic-shell-win10#6]
Currently, I only have a release for the Windows 7-style, but I will eventually include a XP/Classic style with similar features. I have already begun development on it, and the only reason I am referencing this page is because I will be adopting a similar idea with the glyphs in the Classic styles. Everything will be posted [here](https://github.com/bonzibudd/Fluent-Metro) when the first release is ready.

**Comment by davestewart** [comment]
Go for it. I moved to Mac pretty shortly after releasing this, so don't follow what's going on in Windows any more.
