### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by illtellyoulater** [davestewart/classic-shell-win10#8]
Finally!

I can't believe I'm only discovering this project now! 
This is so refreshing... so light to the eyes... so easy to my brain...

Sanity, simplicity, functionality...
This is all I was asking for! 
I really can't thank you enough for this!

How is this not more popular?
Dang... I just saw last commit was from.. 8 years ago?!

A part of me now is getting curious to see if this has been continued somewhere else...
But another and part doesn't feel the slightest hurry to do so...
I'm definitely not going anywhere now...

Because now it's time to appreciate this beautiful feeling of simplicity you gifted me with.
Thank you!

My best wishes of luck for whatever you are doing now in your life.

**Comment by davestewart** [comment]
Ha! No worries, glad you like it.

I moved to Mac probably around the same time, but thought I would get this out.

Enjoy!
